name: build and release
on:
  push:
    tags:
      - "v*"
jobs:
  release_archive:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install deps
        run: |
          sudo apt install -y zip

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Setup xcaddy
        run: |
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Build caddy with plugin
        env:
          CGO_ENABLED: 1
          GOAMD64: v2
        run: |
          make zip

      - name: Create Release
        id: create_release
        uses: shogo82148/actions-create-release@v1

      - name: Upload assets
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: caddy-build.zip
          asset_content_type: application/zip
          overwrite: true
