name: test for build
on:
  push:
    branches:
      - "**"
jobs:
  release_archive:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install deps
        run: |
          sudo apt install -y zip

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Setup xcaddy
        run: |
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Build caddy with plugin
        env:
          CGO_ENABLED: 1
          GOAMD64: v3
        run: |
          make zip
