name: test for build
on:
  push:
    branches:
      - "**"
jobs:
  release_archive:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install deps
        run: |
          sudo apt install -y zip

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: "stable"

      - name: Setup xcaddy
        run: |
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Build caddy with plugin
        env:
          CGO_ENABLED: 0
          GOAMD64: v3
        run: |
          make zip
